Async v2 seems not to terminate when the call fails. The caller seems to keep forever the storage:

```
{
  "454c524f4e44564d404153594e43b83ca32e5773949932897290097c662dd7a70337b9da23d24f35684fb6c40594": "0a2000000000000000000500000000020000000000000000000000000000000000001220b83ca32e5773949932897290097c662dd7a70337b9da23d24f35684fb6c40594222001000000010000000000000000000000000000000000000000000000000000002a20010000000100000000000000000000000000000000000000000000000000000062622a600a20dc12a8053f773ce8ed65505668e2af787eb9359d84db6abf085114bc384edabc18042a20000000000000000005000000000300000000000000000000000000000000000132136e6f6e4578697374656e74456e64706f696e743880ade20468017001",
}
```

which seems to correspond to a callback storage.

# How to reproduce

```bash
npm install

npm run build

npm run test
```
